include /home/y/share/yahoo_cfg/Make.defs
CXXSRC	= ats_fe_validator.cc
LIB_NAME = ats_fe_validator
SHLIB_VERSION = handler
WARN	+= -Werror
LDEF	= 
LINC	= 
LLDLIBS	= -ltshttptxnutil
include /home/y/share/yahoo_cfg/Make.rules
$(SHLIB_NAME_VERSION_O): SHLIB_RPATH += -Wl,-unresolved-symbols=ignore-all
